# Environment variables to be defined in the build configuration:
# AUTH0_TEST_CLIENT_ID = Client id to use in test
# AUTH0_TEST_DOMAIN = Domain to use in test
# AUTH0_TEST_API_IDENTIFIER = API Audience to use in test

# Common logic
defaults: &defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            echo "export const AUTH_CONFIG = {" >> $AUTH0_CFG
            echo "  clientId: '$AUTH0_TEST_CLIENT_ID'," >> $AUTH0_CFG
            echo "  domain: '$AUTH0_TEST_DOMAIN'," >> $AUTH0_CFG
            echo "  callbackUrl: 'http://localhost:3000/callback'," >> $AUTH0_CFG
            echo "  apiUrl: '$AUTH0_TEST_AUDIENCE'" >> $AUTH0_CFG
            echo "}" >> $AUTH0_CFG
          
      - run:
          name: Build pull request
          command: |
            docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
            docker run -d -p 3000:3000 --name $CIRCLE_SHA1 -e AUTH0_DOMAIN=$AUTH0_TEST_DOMAIN -e AUTH0_AUDIENCE=$AUTH0_TEST_API_IDENTIFIER $CIRCLE_JOB
      - run:
          name: Wait for app to be available
          command: |
            sleep 10
            docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:3000
      - run: 
          name: Run tests
          command: |
            docker create --network host --name tester codeception/codeceptjs codeceptjs run-multiple --all --steps --verbose
            docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
          working_directory: scripts
      - run:
          name: Copy app container logs
          command: |
            mkdir -p /tmp/out
            docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
            docker cp tester:/tests/out /tmp/
          when: on_fail
      - store_artifacts:
          path: /tmp/out

# Jobs and Workflows
version: 2
jobs: 
  checkout:
    machine: true
    steps:
      - checkout
      - run: git clone https://github.com/auth0-samples/spa-quickstarts-tests scripts
      - persist_to_workspace:
          root: ~/ 
          paths:
            - project
            - scripts
  01-login:
    machine: true
    environment:
      - AUTH0_CFG: 01-Login/src/Auth/auth0-variables.js
      - SAMPLE_PATH: 01-Login
    <<: *defaults
  02-user-profile:
    machine: true
    environment:
      - AUTH0_CFG: 02-User-Profile/src/Auth/auth0-variables.js
      - SAMPLE_PATH: 02-User-Profile
    <<: *defaults
  03-calling-an-api:
    machine: true
    environment:
      - AUTH0_CFG: 03-Calling-an-API/src/Auth/auth0-variables.js
      - SAMPLE_PATH: 03-Calling-an-API
    <<: *defaults
  04-authorization:
    machine: true
    environment:
      - AUTH0_CFG: 04-Authorization/src/Auth/auth0-variables.js
      - SAMPLE_PATH: 04-Authorization
    <<: *defaults
  05-token-renewal:
    machine: true
    environment:
      - AUTH0_CFG: 05-Token-Renewal/src/Auth/auth0-variables.js
      - SAMPLE_PATH: 05-Token-Renewal
    <<: *defaults

workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart SPA Test
      - 01-login:
          context: Quickstart SPA Test
          requires:
            - checkout
      - 02-user-profile:
          context: Quickstart SPA Test
          requires:
            - checkout
      - 03-calling-an-api:
          context: Quickstart SPA Test
          requires:
            - checkout
      - 04-authorization:
          context: Quickstart SPA Test
          requires:
            - checkout
      - 05-token-renewal:
          context: Quickstart SPA Test
          requires:
            - checkout